import type { AppConfig, GatewayConfig, Slot } from './config.ts';

function normalizeRoutePath(routePath: string): string {
  if (!routePath.startsWith('/')) {
    throw new Error(`Route path must start with '/': ${routePath}`);
  }
  return routePath.endsWith('/') ? routePath : `${routePath}/`;
}

function renderProxyLocation(routePath: string, app: AppConfig): string {
  const prefixHeader = app.stripRoutePrefix ? `\n        proxy_set_header X-Forwarded-Prefix ${routePath};` : '';
  const proxyPass = app.stripRoutePrefix && routePath !== '/'
    ? `http://${app.id}_active/`
    : `http://${app.id}_active`;

  return `
    location ${routePath} {
        proxy_pass ${proxyPass};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
${prefixHeader}
        proxy_set_header Connection "";
    }`.trimEnd();
}

function renderServerBlock(serverNames: string[], locations: string): string {
  return `server {
    listen 80;
    listen [::]:80;
    server_name ${serverNames.join(' ')};
    client_header_buffer_size 16k;
    large_client_header_buffers 4 32k;

    location = /healthz {
        return 200 'ok';
        add_header Content-Type text/plain;
    }

${locations}
}`;
}

function renderDedicatedHostBlock(app: AppConfig): string {
  if (app.hostnames.length === 0) {
    return '';
  }

  return renderServerBlock(
    app.hostnames,
    `
    location / {
        proxy_pass http://${app.id}_active;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }`.trimEnd()
  );
}

export function renderGatewaySite(config: GatewayConfig): string {
  const enabledApps = config.apps.filter((app) => app.enabled);
  const includes = enabledApps
    .map((app) => `include ${app.upstreamConfPath};`)
    .join('\n');

  const appLocations = enabledApps
    .map((app) => renderProxyLocation(normalizeRoutePath(app.routePath), app))
    .join('\n\n');

  const adminRoutePath = config.gateway.adminUi.enabled
    ? normalizeRoutePath(config.gateway.adminUi.routePath)
    : null;
  const adminLocation = adminRoutePath
    ? `
${adminRoutePath !== '/' ? `    location = ${adminRoutePath.slice(0, -1)} {
        return 302 ${adminRoutePath};
    }
` : ''}
    location ${adminRoutePath} {
        proxy_pass http://127.0.0.1:${config.gateway.adminUi.port}/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix ${adminRoutePath};
        proxy_set_header Connection "";
    }`.trimEnd()
    : '';

  const sharedServer = renderServerBlock(
    config.gateway.serverNames,
    [adminLocation, appLocations].filter((value) => value.length > 0).join('\n\n')
  );

  const dedicatedServers = enabledApps
    .map((app) => renderDedicatedHostBlock(app))
    .filter((block) => block.length > 0)
    .join('\n\n');

  return `# Generated by gateway-control-plane
${includes}

${sharedServer}
${dedicatedServers ? `\n\n${dedicatedServers}` : ''}
`;
}

export function renderActiveUpstream(app: AppConfig, slot: Slot): string {
  return `# Generated by gateway-control-plane
upstream ${app.id}_active {
    server 127.0.0.1:${app.slots[slot].port};
    keepalive 32;
}
`;
}
