import type { AppConfig, GatewayConfig, Slot } from './config.ts';

function normalizeRoutePath(routePath: string): string {
  if (!routePath.startsWith('/')) {
    throw new Error(`Route path must start with '/': ${routePath}`);
  }
  return routePath.endsWith('/') ? routePath : `${routePath}/`;
}

export function renderGatewaySite(config: GatewayConfig): string {
  const enabledApps = config.apps.filter((app) => app.enabled);
  const includes = enabledApps
    .map((app) => `include ${app.upstreamConfPath};`)
    .join('\n');

  const locations = enabledApps
    .map((app) => {
      const routePath = normalizeRoutePath(app.routePath);
      const prefixHeader = app.stripRoutePrefix ? `\n        proxy_set_header X-Forwarded-Prefix ${routePath};` : '';
      const proxyPass = app.stripRoutePrefix && routePath !== '/'
        ? `http://${app.id}_active/`
        : `http://${app.id}_active`;
      return `
    location ${routePath} {
        proxy_pass ${proxyPass};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
${prefixHeader}
        proxy_set_header Connection "";
    }`.trimEnd();
    })
    .join('\n\n');

  const adminRoutePath = config.gateway.adminUi.enabled
    ? normalizeRoutePath(config.gateway.adminUi.routePath)
    : null;
  const adminLocation = adminRoutePath
    ? `
${adminRoutePath !== '/' ? `    location = ${adminRoutePath.slice(0, -1)} {
        return 302 ${adminRoutePath};
    }
` : ''}
    location ${adminRoutePath} {
        proxy_pass http://127.0.0.1:${config.gateway.adminUi.port}/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix ${adminRoutePath};
        proxy_set_header Connection "";
    }`.trimEnd()
    : '';
  const allLocations = [adminLocation, locations].filter((value) => value.length > 0).join('\n\n');

  return `# Generated by gateway-control-plane
${includes}

server {
    listen 80;
    listen [::]:80;
    server_name ${config.gateway.serverNames.join(' ')};

    location = /healthz {
        return 200 'ok';
        add_header Content-Type text/plain;
    }

${allLocations}
}
`;
}

export function renderActiveUpstream(app: AppConfig, slot: Slot): string {
  return `# Generated by gateway-control-plane
upstream ${app.id}_active {
    server 127.0.0.1:${app.slots[slot].port};
    keepalive 32;
}
`;
}
