import type { AppConfig, GatewayConfig, Slot } from './config.ts';

function normalizeRoutePath(routePath: string): string {
  if (!routePath.startsWith('/')) {
    throw new Error(`Route path must start with '/': ${routePath}`);
  }
  return routePath.endsWith('/') ? routePath : `${routePath}/`;
}

export function renderGatewaySite(config: GatewayConfig): string {
  const includes = config.apps
    .map((app) => `include ${app.upstreamConfPath};`)
    .join('\n');

  const locations = config.apps
    .map((app) => {
      const routePath = normalizeRoutePath(app.routePath);
      return `
    location ${routePath} {
        proxy_pass http://${app.id}_active;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
    }`.trimEnd();
    })
    .join('\n\n');

  return `# Generated by gateway-control-plane
${includes}

server {
    listen 80;
    listen [::]:80;
    server_name ${config.gateway.serverNames.join(' ')};

    location = /healthz {
        return 200 'ok';
        add_header Content-Type text/plain;
    }

${locations}
}
`;
}

export function renderActiveUpstream(app: AppConfig, slot: Slot): string {
  return `# Generated by gateway-control-plane
upstream ${app.id}_active {
    server 127.0.0.1:${app.slots[slot].port};
    keepalive 32;
}
`;
}

